name: panoptes-data
channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - astropy
  - h5py
  - numpy
  - pandas
  - photutils
  - pip
  - pydantic
  - python-dateutil
  - scipy
  - tqdm
  - uvicorn
  - pip:
      - -e .
      - "git+https://github.com/panoptes/panoptes-utils@develop#egg=panoptes-utils[config,images,social]"
