name: panoptes-data
channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - astropy
  - google-cloud-storage
  - numpy
  - pandas
  - pip
  - pydantic
  - python-dateutil
  - tqdm
  - pip:
      - "git+https://github.com/panoptes/panoptes-utils@develop#egg=panoptes-utils"
