name: panoptes-data
channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - astropy
  - numpy
  - pandas
  - pip
  - pydantic
  - python-dateutil
  - tqdm
  - typer
  - pip:
      - .
      - panoptes-utils[images]
